#!/system/bin/sh
#
# parts taken from "screenstate_scaling" by florian.schaefer & "battery tweak" by collin_ph@xda
# by freeza for freEVO 3D ROM

AWAKE_MODE() # Screen-ON
{
# VM parameters
BTLF=`cat /sys/class/power_supply/battery/capacity`
BTST=`cat /sys/class/power_supply/battery/status`
if [ "$BTST" == "Charging" ] || [ "$BTST" == "Full" ]; then
	echo 1620000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
	echo 1620000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq;
	echo "60" > /sys/devices/system/cpu/cpufreq/IntelliAnthraX/up_threshold;
	echo "40000" > /sys/devices/system/cpu/cpufreq/IntelliAnthraX/sampling_rate;
else
if [ "$BTLF" -ge 0 ] && [ "$BTLF" -lt 30 ]; then
	echo 192000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
	echo 810000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq;
	echo "90" /sys/devices/system/cpu/cpufreq/IntelliAnthraX/up_threshold;
	echo "120000" > /sys/devices/system/cpu/cpufreq/IntelliAnthraX/sampling_rate;
	echo "1" > /sys/devices/system/cpu/cpufreq/IntelliAnthraX/sampling_down_factor;
	echo "5" > /sys/devices/system/cpu/cpufreq/IntelliAnthraX/down_differential;
fi
fi
	echo -1 > /proc/sys/kernel/sched_rt_runtime_us;
	echo 100000 > /proc/sys/kernel/sched_rt_period_us;
	echo 95000 > /proc/sys/kernel/sched_rt_runtime_us;
	echo 30 > /proc/sys/vm/swappiness;
	echo 1000 > /proc/sys/vm/dirty_expire_centisecs;
	echo 2000 > /proc/sys/vm/dirty_writeback_centisecs;
	echo 10 > /proc/sys/vm/dirty_background_ratio;
	echo 40 > /proc/sys/vm/dirty_ratio;
	echo 0 > /proc/sys/vm/page-cluster;
	echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
	echo 0 > /proc/sys/vm/laptop_mode;
	echo 300 > /proc/sys/vm/vfs_cache_pressure;
	echo 8192 > /proc/sys/vm/min_free_kbytes;
}

SLEEP_MODE()# Screen-OFF
{
# VM parameters
BTSTo=`cat /sys/class/power_supply/battery/status`
if [ "$BTSTo" == "Charging" ] || [ "$BTSTo" == "Full" ]; then
	echo 1620000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
	echo 1620000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq;
else
	echo 810000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
fi
	echo -1 > /proc/sys/kernel/sched_rt_runtime_us;
	echo 1000000 > /proc/sys/kernel/sched_rt_period_us;
	echo 950000 > /proc/sys/kernel/sched_rt_runtime_us;
	echo 0 > /proc/sys/vm/swappiness;
	echo 0 > /proc/sys/vm/dirty_expire_centisecs;
	echo 0 > /proc/sys/vm/dirty_writeback_centisecs;
	echo 60 > /proc/sys/vm/dirty_background_ratio;
	echo 95 > /proc/sys/vm/dirty_ratio;
	echo 3 > /proc/sys/vm/page-cluster;
	echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
	echo 5 > /proc/sys/vm/laptop_mode;
	echo 10 > /proc/sys/vm/vfs_cache_pressure;
	echo 2048 > /proc/sys/vm/min_free_kbytes;
}
	
MAX_PHONE() # remove lag when answering phone calls
{
pidphone=`pidof com.android.phone`;
if [ $pidphone ];
then
	echo -17 > /proc/$pidphone/oom_adj; # exclude com.android.phone from oom-killer
	renice -20 $pidphone; # set highest nice level for com.android.phone
	exit;
else
	sleep 1;
	MAX_PHONE;
fi;
}

# Background process to check screen state
	(while [ 1 ]; 
	do
		cat /sys/power/wait_for_fb_wake;
		AWAKE_MODE;

		cat /sys/power/wait_for_fb_sleep;
		SLEEP_MODE;
	done &);

# One-time process to optimize com.android.phone
	(while [ 1 ];
	do
		sleep 10;
		MAX_PHONE;
	done &);
