#!/system/bin/sh

#Check if tun kernel module is present
#insert it if it is.
if [ -e /system/lib/modules/tun.ko ] ; then
	insmod /system/lib/modules/tun.ko
	echo "[91TUN]: Inserted tun kernel module.";
else
	echo "[91TUN]: No tun kernel module found.";
fi

